<?php

namespace Database\Seeders;

use App\Models\Participant;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ParticipantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $participants = [
            [
                "edition_id" => 1,
                "song" => "Discoteque",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 1,
                "final_order" => 18,
                "country_id" => 21,
            ],
            [
                "edition_id" => 1,
                "song" => "Amen",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 2,
                "final_order" => null,
                "country_id" => 36,
            ],
            [
                "edition_id" => 1,
                "song" => "Russian woman",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 3,
                "final_order" => 5,
                "country_id" => 33,
            ],
            [
                "edition_id" => 1,
                "song" => "Voices",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 4,
                "final_order" => 25,
                "country_id" => 40,
            ],
            [
                "edition_id" => 1,
                "song" => "Technicolour",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 5,
                "final_order" => null,
                "country_id" => 3,
            ],
            [
                "edition_id" => 1,
                "song" => "Here I stand",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 6,
                "final_order" => null,
                "country_id" => 26,
            ],
            [
                "edition_id" => 1,
                "song" => "MAPS",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 7,
                "final_order" => null,
                "country_id" => 15,
            ],
            [
                "edition_id" => 1,
                "song" => "El Diablo",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 8,
                "final_order" => 1,
                "country_id" => 7,
            ],
            [
                "edition_id" => 1,
                "song" => "Fallen angel",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 9,
                "final_order" => 22,
                "country_id" => 27,
            ],
            [
                "edition_id" => 1,
                "song" => "Tick-tock",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 10,
                "final_order" => null,
                "country_id" => 19,
            ],
            [
                "edition_id" => 1,
                "song" => "The wrong place",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 11,
                "final_order" => 4,
                "country_id" => 5,
            ],
            [
                "edition_id" => 1,
                "song" => "Set me free",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 12,
                "final_order" => 3,
                "country_id" => 17,
            ],
            [
                "edition_id" => 1,
                "song" => "Amnesia",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 13,
                "final_order" => null,
                "country_id" => 32,
            ],
            [
                "edition_id" => 1,
                "song" => "Mata Hari",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 14,
                "final_order" => 21,
                "country_id" => 4,
            ],
            [
                "edition_id" => 1,
                "song" => "Sjoem",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 15,
                "final_order" => 19,
                "country_id" => 28,
            ],
            [
                "edition_id" => 1,
                "song" => "Je me casse",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 16,
                "final_order" => 6,
                "country_id" => 22,
            ],
            [
                "edition_id" => 1,
                "song" => "Adrenalina",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 1,
                "final_order" => 26,
                "country_id" => 34,
            ],
            [
                "edition_id" => 1,
                "song" => "The lucky one",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 2,
                "final_order" => null,
                "country_id" => 10,
            ],
            [
                "edition_id" => 1,
                "song" => "Omaga",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 3,
                "final_order" => null,
                "country_id" => 38,
            ],
            [
                "edition_id" => 1,
                "song" => "Last dance",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 4,
                "final_order" => 10,
                "country_id" => 14,
            ],
            [
                "edition_id" => 1,
                "song" => "Amen",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 5,
                "final_order" => null,
                "country_id" => 29,
            ],
            [
                "edition_id" => 1,
                "song" => "The ride",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 6,
                "final_order" => null,
                "country_id" => 30,
            ],
            [
                "edition_id" => 1,
                "song" => "SUGAR",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 7,
                "final_order" => 14,
                "country_id" => 23,
            ],
            [
                "edition_id" => 1,
                "song" => "10 Years",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 8,
                "final_order" => 12,
                "country_id" => 16,
            ],
            [
                "edition_id" => 1,
                "song" => "Loco loco",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 9,
                "final_order" => 8,
                "country_id" => 35,
            ],
            [
                "edition_id" => 1,
                "song" => "You",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 10,
                "final_order" => null,
                "country_id" => 13,
            ],
            [
                "edition_id" => 1,
                "song" => "Karma",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 11,
                "final_order" => 2,
                "country_id" => 1,
            ],
            [
                "edition_id" => 1,
                "song" => "Love is on my side",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 12,
                "final_order" => 7,
                "country_id" => 31,
            ],
            [
                "edition_id" => 1,
                "song" => "Growing up is getting old",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 13,
                "final_order" => 17,
                "country_id" => 6,
            ],
            [
                "edition_id" => 1,
                "song" => "Dark side",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 14,
                "final_order" => 16,
                "country_id" => 11,
            ],
            [
                "edition_id" => 1,
                "song" => "The Moon is rising",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 15,
                "final_order" => null,
                "country_id" => 20,
            ],
            [
                "edition_id" => 1,
                "song" => "Tout l'Univers",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 16,
                "final_order" => 11,
                "country_id" => 41,
            ],
            [
                "edition_id" => 1,
                "song" => "Øve os på hinanden",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 17,
                "final_order" => null,
                "country_id" => 8,
            ],
            [
                "edition_id" => 1,
                "song" => "Birth of a new age",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 23,
                "country_id" => 25,
            ],
            [
                "edition_id" => 1,
                "song" => "I don't feel hate",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 15,
                "country_id" => 9,
            ],
            [
                "edition_id" => 1,
                "song" => "Voilà",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 20,
                "country_id" => 12,
            ],
            [
                "edition_id" => 1,
                "song" => "Zitti e buoni",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 24,
                "country_id" => 18,
            ],
            [
                "edition_id" => 1,
                "song" => "Voy a quedarme",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 13,
                "country_id" => 37,
            ],
            [
                "edition_id" => 1,
                "song" => "Embers",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 9,
                "country_id" => 39,
            ],
            [
                "edition_id" => 2,
                "song" => "Sekret",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 1,
                "final_order" => null,
                "country_id" => 1,
            ],
            [
                "edition_id" => 2,
                "song" => "Eat Your Salad",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 2,
                "final_order" => null,
                "country_id" => 20,
            ],
            [
                "edition_id" => 2,
                "song" => "Sentimental",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 3,
                "final_order" => 14,
                "country_id" => 21,
            ],
            [
                "edition_id" => 2,
                "song" => "Boys Do Cry",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 4,
                "final_order" => 5,
                "country_id" => 41,
            ],
            [
                "edition_id" => 2,
                "song" => "Disko",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 5,
                "final_order" => null,
                "country_id" => 36,
            ],
            [
                "edition_id" => 2,
                "song" => "Stefania",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 6,
                "final_order" => 12,
                "country_id" => 28,
            ],
            [
                "edition_id" => 2,
                "song" => "Intention",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 7,
                "final_order" => null,
                "country_id" => 6,
            ],
            [
                "edition_id" => 2,
                "song" => "De diepte",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 8,
                "final_order" => 11,
                "country_id" => 25,
            ],
            [
                "edition_id" => 2,
                "song" => "Trenulețul",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 9,
                "final_order" => 19,
                "country_id" => 23,
            ],
            [
                "edition_id" => 2,
                "song" => "Saudade, saudade",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 10,
                "final_order" => 3,
                "country_id" => 31,
            ],
            [
                "edition_id" => 2,
                "song" => "Guilty Pleasure",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 11,
                "final_order" => null,
                "country_id" => 19,
            ],
            [
                "edition_id" => 2,
                "song" => "The Show",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 12,
                "final_order" => null,
                "country_id" => 8,
            ],
            [
                "edition_id" => 2,
                "song" => "Halo",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 13,
                "final_order" => null,
                "country_id" => 29,
            ],
            [
                "edition_id" => 2,
                "song" => "Með hækkandi sól",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 14,
                "final_order" => 18,
                "country_id" => 16,
            ],
            [
                "edition_id" => 2,
                "song" => "Die Together",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 15,
                "final_order" => 17,
                "country_id" => 14,
            ],
            [
                "edition_id" => 2,
                "song" => "Give That Wolf a Banana",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 16,
                "final_order" => 7,
                "country_id" => 27,
            ],
            [
                "edition_id" => 2,
                "song" => "Snap",
                "semi_final" => 1,
                "is_in_final" => TRUE,
                "semi_final_order" => 17,
                "final_order" => 8,
                "country_id" => 2,
            ],
            [
                "edition_id" => 2,
                "song" => "Jezebel",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 1,
                "final_order" => 4,
                "country_id" => 11,
            ],
            [
                "edition_id" => 2,
                "song" => "I.M",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 2,
                "final_order" => null,
                "country_id" => 17,
            ],
            [
                "edition_id" => 2,
                "song" => "In corpore sano",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 3,
                "final_order" => 24,
                "country_id" => 35,
            ],
            [
                "edition_id" => 2,
                "song" => "Fade to Black",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 4,
                "final_order" => 15,
                "country_id" => 4,
            ],
            [
                "edition_id" => 2,
                "song" => "Lock Me In",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 5,
                "final_order" => null,
                "country_id" => 13,
            ],
            [
                "edition_id" => 2,
                "song" => "I Am What I Am",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 6,
                "final_order" => null,
                "country_id" => 22,
            ],
            [
                "edition_id" => 2,
                "song" => "Stripper",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 7,
                "final_order" => null,
                "country_id" => 34,
            ],
            [
                "edition_id" => 2,
                "song" => "Not the Same",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 8,
                "final_order" => 21,
                "country_id" => 3,
            ],
            [
                "edition_id" => 2,
                "song" => "Ela",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 9,
                "final_order" => null,
                "country_id" => 7,
            ],
            [
                "edition_id" => 2,
                "song" => "That's Rich",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 10,
                "final_order" => null,
                "country_id" => 15,
            ],
            [
                "edition_id" => 2,
                "song" => "Circles",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 11,
                "final_order" => null,
                "country_id" => 26,
            ],
            [
                "edition_id" => 2,
                "song" => "Hope",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 12,
                "final_order" => 25,
                "country_id" => 10,
            ],
            [
                "edition_id" => 2,
                "song" => "Llámame",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 13,
                "final_order" => 2,
                "country_id" => 32,
            ],
            [
                "edition_id" => 2,
                "song" => "River",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 14,
                "final_order" => 23,
                "country_id" => 30,
            ],
            [
                "edition_id" => 2,
                "song" => "Breathe",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 15,
                "final_order" => null,
                "country_id" => 24,
            ],
            [
                "edition_id" => 2,
                "song" => "Miss You",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 16,
                "final_order" => 16,
                "country_id" => 5,
            ],
            [
                "edition_id" => 2,
                "song" => "Hold Me Closer",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 17,
                "final_order" => 20,
                "country_id" => 40,
            ],
            [
                "edition_id" => 2,
                "song" => "Lights Off",
                "semi_final" => 2,
                "is_in_final" => TRUE,
                "semi_final_order" => 18,
                "final_order" => 1,
                "country_id" => 38,
            ],
            [
                "edition_id" => 2,
                "song" => "Brividi",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 9,
                "country_id" => 18,
            ],
            [
                "edition_id" => 2,
                "song" => "Fulenn",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 6,
                "country_id" => 12,
            ],
            [
                "edition_id" => 2,
                "song" => "Rockstars",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 13,
                "country_id" => 9,
            ],
            [
                "edition_id" => 2,
                "song" => "SloMo",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 10,
                "country_id" => 37,
            ],
            [
                "edition_id" => 2,
                "song" => "Space Man",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 22,
                "country_id" => 39,
            ],
            [
                "edition_id" => 3,
                "song" => "Queen of Kings",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 1,
                "final_order" => null,
                "country_id" => 27,
            ],
            [
                "edition_id" => 3,
                "song" => "Dance (Our Own Party)",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 2,
                "final_order" => null,
                "country_id" => 22,
            ],
            [
                "edition_id" => 3,
                "song" => "Samo mi se spava",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 3,
                "final_order" => null,
                "country_id" => 35,
            ],
            [
                "edition_id" => 3,
                "song" => "Aijā",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 4,
                "final_order" => null,
                "country_id" => 20,
            ],
            [
                "edition_id" => 3,
                "song" => "Ai coração",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 5,
                "final_order" => null,
                "country_id" => 31,
            ],
            [
                "edition_id" => 3,
                "song" => "We Are One",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 6,
                "final_order" => null,
                "country_id" => 15,
            ],
            [
                "edition_id" => 3,
                "song" => "Mama ŠČ!",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 7,
                "final_order" => null,
                "country_id" => 19,
            ],
            [
                "edition_id" => 3,
                "song" => "Watergun",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 8,
                "final_order" => null,
                "country_id" => 41,
            ],
            [
                "edition_id" => 3,
                "song" => "Unicorn",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 9,
                "final_order" => null,
                "country_id" => 17,
            ],
            [
                "edition_id" => 3,
                "song" => "Soarele și luna",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 10,
                "final_order" => null,
                "country_id" => 23,
            ],
            [
                "edition_id" => 3,
                "song" => "Tattoo",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 11,
                "final_order" => null,
                "country_id" => 40,
            ],
            [
                "edition_id" => 3,
                "song" => "Tell Me More",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 12,
                "final_order" => null,
                "country_id" => 4,
            ],
            [
                "edition_id" => 3,
                "song" => "My Sister's Crown",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 13,
                "final_order" => null,
                "country_id" => 38,
            ],
            [
                "edition_id" => 3,
                "song" => "Burning Daylight",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 14,
                "final_order" => null,
                "country_id" => 25,
            ],
            [
                "edition_id" => 3,
                "song" => "Cha Cha Cha",
                "semi_final" => 1,
                "is_in_final" => FALSE,
                "semi_final_order" => 15,
                "final_order" => null,
                "country_id" => 11,
            ],
            [
                "edition_id" => 3,
                "song" => "Breaking My Heart",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 1,
                "final_order" => null,
                "country_id" => 8,
            ],
            [
                "edition_id" => 3,
                "song" => "Future Lover",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 2,
                "final_order" => null,
                "country_id" => 2,
            ],
            [
                "edition_id" => 3,
                "song" => "D.G.T. (Off and On)",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 3,
                "final_order" => null,
                "country_id" => 32,
            ],
            [
                "edition_id" => 3,
                "song" => "Bridges",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 4,
                "final_order" => null,
                "country_id" => 10,
            ],
            [
                "edition_id" => 3,
                "song" => "Because of You",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 5,
                "final_order" => null,
                "country_id" => 5,
            ],
            [
                "edition_id" => 3,
                "song" => "Break a Broken Heart",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 6,
                "final_order" => null,
                "country_id" => 7,
            ],
            [
                "edition_id" => 3,
                "song" => "Power",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 7,
                "final_order" => null,
                "country_id" => 16,
            ],
            [
                "edition_id" => 3,
                "song" => "What They Say",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 8,
                "final_order" => null,
                "country_id" => 14,
            ],
            [
                "edition_id" => 3,
                "song" => "Solo",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 9,
                "final_order" => null,
                "country_id" => 30,
            ],
            [
                "edition_id" => 3,
                "song" => "Carpe Diem",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 10,
                "final_order" => null,
                "country_id" => 36,
            ],
            [
                "edition_id" => 3,
                "song" => "Echo",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 11,
                "final_order" => null,
                "country_id" => 13,
            ],
            [
                "edition_id" => 3,
                "song" => "Like an Animal",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 12,
                "final_order" => null,
                "country_id" => 34,
            ],
            [
                "edition_id" => 3,
                "song" => "Who the Hell Is Edgar",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 13,
                "final_order" => null,
                "country_id" => 29,
            ],
            [
                "edition_id" => 3,
                "song" => "Duje",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 14,
                "final_order" => null,
                "country_id" => 1,
            ],
            [
                "edition_id" => 3,
                "song" => "Stay",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 15,
                "final_order" => null,
                "country_id" => 21,
            ],
            [
                "edition_id" => 3,
                "song" => "Promise",
                "semi_final" => 2,
                "is_in_final" => FALSE,
                "semi_final_order" => 16,
                "final_order" => null,
                "country_id" => 3,
            ],
            [
                "edition_id" => 3,
                "song" => "Évidemment",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => null,
                "country_id" => 12,
            ],
            [
                "edition_id" => 3,
                "song" => "Blood & Glitter",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => null,
                "country_id" => 9,
            ],
            [
                "edition_id" => 3,
                "song" => "Due vite",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => null,
                "country_id" => 18,
            ],
            [
                "edition_id" => 3,
                "song" => "Eaea",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => null,
                "country_id" => 37,
            ],
            [
                "edition_id" => 3,
                "song" => "Heart of Steel",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 19,
                "country_id" => 28,
            ],
            [
                "edition_id" => 3,
                "song" => "I Wrote a Song",
                "semi_final" => null,
                "is_in_final" => TRUE,
                "semi_final_order" => null,
                "final_order" => 26,
                "country_id" => 39,
            ],
        ];

        Schema::disableForeignKeyConstraints();
        DB::table('participants')->truncate();
        foreach ($participants as $participant) {
            Participant::create($participant);
        }
        Schema::enableForeignKeyConstraints();
    }
}
